### ISSUE TITLE
Warmup ex 10

### ISSUE THREAD

**Issue by emilcphu** [Kristianuruplarsen/sdseml_online_exercises#448]
Hi Kristian,

I have trouble understanding your instruction on how to generate the sequence in Q1. I understand what the sequence should look like. However, it's not clear to me what you mean by the z values and how exactly to perform the drawings of x and y based on the z difference. 

Could you perhaps reveal some code on what your idea is ? It would make it a lot easier to figure out, what your intention is. Also, it is kinda difficult to do Q2 and Q3 without an understanding of Q1 :).

/Emil

**Comment by kristianolesenlarsen** [comment]
Yeah sorry - it is very densely written. The problem is essentially a discrete version of problem 21 [in this problem set](https://arxiv.org/pdf/1110.1556.pdf).

What i mean by *z_{k+1} - z_k ~ U(0, 2/n)* is that the distance from *z_k* to *z_{k+1}* is uniformly drawn between _0_ and _2/n_. _z_ is either _x_ or _y_. So in code you would want something like 
```python
x0 = np.random.uniform(0, 2/n) 
y0 = np.random.uniform(0, 2/n) 
x, y = [x0], [y0] 
for _ in range(n-1): 
    x0 = x0 + np.random.uniform(0,2/n) 
    y0 = y0 + np.random.uniform(0,2/n) 
    x.append(x0 if x0 < 1 else 1) 
    y.append(y0 if y0 < 1 else 1)
```
I hope this makes sense, otherwise get back to me!

**Comment by emilcphu** [comment]
Thanks Kristian!
