### ISSUE TITLE
Ex. 6.1.6

### ISSUE THREAD

**Issue by signehaahr** [Kristianuruplarsen/sdseml_online_exercises#49]
Hi,

I'm trying to solve Ex. 6.1.6, but I get the error message in the picture below, and I can't figure out how to solve the problem. 

In my `simulate()` function I return `[y, d, x, z, u, nu, alpha, delta, Pi, gamma]`

<img width="416" alt="p1" src="https://user-images.githubusercontent.com/60400073/77565667-da19f100-6ec4-11ea-9b76-04392c4ad258.PNG">

Best,
Signe

**Comment by kristianolesenlarsen** [comment]
It looks like you are supplying a column of data to `force_include_idx`. You need to concatenate `x` and `z` into one matrix (fit only takes X,y as inputs) and keep track of which column indices contain `x`. You can then supply these column indices as `force_include_idx`.

Under the if-statement in `PostLasso.fit` you will see then that the `subset_cols` used in the OLS step are set as the union of those picked by the lasso and those you supplied in `force_include_idx`.

I hope this makes sense, otherwise get back to me and i will try to clarify!
